### ISSUE TITLE
Problem building on CoreOS 899.9.0

### ISSUE THREAD

**Issue by themicster** [dougbtv/docker-asterisk#47] opened 2016-05-14 21:18 UTC
```
core@sea2-cn1 /var/data/containers $ git clone https://github.com/dougbtv/docker-asterisk.git
Cloning into 'docker-asterisk'...
remote: Counting objects: 1592, done.
remote: Total 1592 (delta 0), reused 0 (delta 0), pack-reused 1592
Receiving objects: 100% (1592/1592), 1.69 MiB | 2.04 MiB/s, done.
Resolving deltas: 100% (894/894), done.
Checking connectivity... done.
core@sea2-cn1 /var/data/containers $ cd docker-asterisk
core@sea2-cn1 /var/data/containers/docker-asterisk $ ls
Dockerfile  README.md  asterisk  fastagi  high-availability  test  tools
core@sea2-cn1 /var/data/containers/docker-asterisk $ docker build --no-cache -t dougbtv/docker-asterisk .
Sending build context to Docker daemon 3.559 MB
Step 0 : FROM centos:centos6
 ---> 2f96ee8baf17
Step 1 : MAINTAINER Doug Smith <info@laboratoryb.org>
 ---> Running in 9ff89392f760
 ---> cd9c932d3d16
Removing intermediate container 9ff89392f760
Step 2 : ENV build_date 2016-04-06
 ---> Running in 60c8ed512f78
 ---> 2f54e47e9ee4
Removing intermediate container 60c8ed512f78
Step 3 : RUN yum update -y
 ---> Running in 7fde8b718beb
Loaded plugins: fastestmirror
Setting up Update Process
Resolving Dependencies
--> Running transaction check
---> Package kernel-firmware.noarch 0:2.6.32-573.22.1.el6 will be updated
---> Package kernel-firmware.noarch 0:2.6.32-573.26.1.el6 will be an update
---> Package nspr.x86_64 0:4.10.8-2.el6_7 will be updated
---> Package nspr.x86_64 0:4.11.0-0.1.el6_7 will be an update
---> Package nss.x86_64 0:3.19.1-8.el6_7 will be updated
---> Package nss.x86_64 0:3.21.0-0.3.el6_7 will be an update
---> Package nss-sysinit.x86_64 0:3.19.1-8.el6_7 will be updated
---> Package nss-sysinit.x86_64 0:3.21.0-0.3.el6_7 will be an update
---> Package nss-tools.x86_64 0:3.19.1-8.el6_7 will be updated
---> Package nss-tools.x86_64 0:3.21.0-0.3.el6_7 will be an update
---> Package nss-util.x86_64 0:3.19.1-5.el6_7 will be updated
---> Package nss-util.x86_64 0:3.21.0-0.3.el6_7 will be an update
---> Package tzdata.noarch 0:2016c-1.el6 will be updated
---> Package tzdata.noarch 0:2016d-1.el6 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package              Arch        Version                    Repository    Size
================================================================================
Updating:
 kernel-firmware      noarch      2.6.32-573.26.1.el6        updates       18 M
 nspr                 x86_64      4.11.0-0.1.el6_7           updates      114 k
 nss                  x86_64      3.21.0-0.3.el6_7           updates      858 k
 nss-sysinit          x86_64      3.21.0-0.3.el6_7           updates       46 k
 nss-tools            x86_64      3.21.0-0.3.el6_7           updates      435 k
 nss-util             x86_64      3.21.0-0.3.el6_7           updates       67 k
 tzdata               noarch      2016d-1.el6                updates      451 k

Transaction Summary
================================================================================
Upgrade       7 Package(s)

Total download size: 20 M
Downloading Packages:
--------------------------------------------------------------------------------
Total                                           3.4 MB/s |  20 MB     00:05
warning: rpmts_HdrFromFdno: Header V3 RSA/SHA1 Signature, key ID c105b9de: NOKEY
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6
Importing GPG key 0xC105B9DE:
 Userid : CentOS-6 Key (CentOS 6 Official Signing Key) <centos-6-key@centos.org>
 Package: centos-release-6-7.el6.centos.12.3.x86_64 (@CentOS/6.7)
 From   : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Updating   : nspr-4.11.0-0.1.el6_7.x86_64                                1/14
  Updating   : nss-util-3.21.0-0.3.el6_7.x86_64                            2/14
  Updating   : nss-3.21.0-0.3.el6_7.x86_64                                 3/14
  Updating   : nss-sysinit-3.21.0-0.3.el6_7.x86_64                         4/14
  Updating   : nss-tools-3.21.0-0.3.el6_7.x86_64                           5/14
  Updating   : tzdata-2016d-1.el6.noarch                                   6/14
  Updating   : kernel-firmware-2.6.32-573.26.1.el6.noarch                  7/14
  Cleanup    : tzdata-2016c-1.el6.noarch                                   8/14
  Cleanup    : kernel-firmware-2.6.32-573.22.1.el6.noarch                  9/14
  Cleanup    : nss-tools-3.19.1-8.el6_7.x86_64                            10/14
  Cleanup    : nss-3.19.1-8.el6_7.x86_64                                  11/14
  Cleanup    : nss-sysinit-3.19.1-8.el6_7.x86_64                          12/14
  Cleanup    : nss-util-3.19.1-5.el6_7.x86_64                             13/14
  Cleanup    : nspr-4.10.8-2.el6_7.x86_64                                 14/14
  Verifying  : kernel-firmware-2.6.32-573.26.1.el6.noarch                  1/14
  Verifying  : nss-sysinit-3.21.0-0.3.el6_7.x86_64                         2/14
  Verifying  : nss-tools-3.21.0-0.3.el6_7.x86_64                           3/14
  Verifying  : nss-util-3.21.0-0.3.el6_7.x86_64                            4/14
  Verifying  : nss-3.21.0-0.3.el6_7.x86_64                                 5/14
  Verifying  : tzdata-2016d-1.el6.noarch                                   6/14
  Verifying  : nspr-4.11.0-0.1.el6_7.x86_64                                7/14
  Verifying  : nss-3.19.1-8.el6_7.x86_64                                   8/14
  Verifying  : nspr-4.10.8-2.el6_7.x86_64                                  9/14
  Verifying  : nss-util-3.19.1-5.el6_7.x86_64                             10/14
  Verifying  : kernel-firmware-2.6.32-573.22.1.el6.noarch                 11/14
  Verifying  : nss-tools-3.19.1-8.el6_7.x86_64                            12/14
  Verifying  : nss-sysinit-3.19.1-8.el6_7.x86_64                          13/14
  Verifying  : tzdata-2016c-1.el6.noarch                                  14/14

Updated:
  kernel-firmware.noarch 0:2.6.32-573.26.1.el6
  nspr.x86_64 0:4.11.0-0.1.el6_7
  nss.x86_64 0:3.21.0-0.3.el6_7
  nss-sysinit.x86_64 0:3.21.0-0.3.el6_7
  nss-tools.x86_64 0:3.21.0-0.3.el6_7
  nss-util.x86_64 0:3.21.0-0.3.el6_7
  tzdata.noarch 0:2016d-1.el6

Complete!
 ---> 4c7f83572e72
Removing intermediate container 7fde8b718beb
Step 4 : RUN yum install kernel-headers gcc gcc-c++ cpp ncurses ncurses-devel libxml2 libxml2-devel sqlite sqlite-devel openssl-devel newt-devel kernel-devel libuuid-devel net-snmp-devel xinetd tar -y
 ---> Running in 995f7482ea04
Loaded plugins: fastestmirror
Setting up Install Process
Determining fastest mirrors
 * base: ftpmirror.your.org
 * extras: lug.mtu.edu
 * updates: mirror.spro.net
Package ncurses-5.7-4.20090207.el6.x86_64 already installed and latest version
Package libxml2-2.7.6-20.el6_7.1.x86_64 already installed and latest version
Package sqlite-3.6.20-1.el6_7.2.x86_64 already installed and latest version
Package 2:tar-1.23-13.el6.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package cpp.x86_64 0:4.4.7-16.el6 will be installed
--> Processing Dependency: libmpfr.so.1()(64bit) for package: cpp-4.4.7-16.el6.x86_64
---> Package gcc.x86_64 0:4.4.7-16.el6 will be installed
--> Processing Dependency: libgomp = 4.4.7-16.el6 for package: gcc-4.4.7-16.el6.x86_64
--> Processing Dependency: glibc-devel >= 2.2.90-12 for package: gcc-4.4.7-16.el6.x86_64
--> Processing Dependency: cloog-ppl >= 0.15 for package: gcc-4.4.7-16.el6.x86_64
--> Processing Dependency: libgomp.so.1()(64bit) for package: gcc-4.4.7-16.el6.x86_64
---> Package gcc-c++.x86_64 0:4.4.7-16.el6 will be installed
--> Processing Dependency: libstdc++-devel = 4.4.7-16.el6 for package: gcc-c++-4.4.7-16.el6.x86_64
---> Package kernel-devel.x86_64 0:2.6.32-573.26.1.el6 will be installed
---> Package kernel-headers.x86_64 0:2.6.32-573.26.1.el6 will be installed
---> Package libuuid-devel.x86_64 0:2.17.2-12.18.el6 will be installed
---> Package libxml2-devel.x86_64 0:2.7.6-20.el6_7.1 will be installed
--> Processing Dependency: zlib-devel for package: libxml2-devel-2.7.6-20.el6_7.1.x86_64
---> Package ncurses-devel.x86_64 0:5.7-4.20090207.el6 will be installed
---> Package net-snmp-devel.x86_64 1:5.5-54.el6_7.1 will be installed
--> Processing Dependency: net-snmp-libs = 1:5.5-54.el6_7.1 for package: 1:net-snmp-devel-5.5-54.el6_7.1.x86_64
--> Processing Dependency: tcp_wrappers-devel for package: 1:net-snmp-devel-5.5-54.el6_7.1.x86_64
--> Processing Dependency: rpm-devel for package: 1:net-snmp-devel-5.5-54.el6_7.1.x86_64
--> Processing Dependency: lm_sensors-devel for package: 1:net-snmp-devel-5.5-54.el6_7.1.x86_64
--> Processing Dependency: elfutils-libelf-devel for package: 1:net-snmp-devel-5.5-54.el6_7.1.x86_64
--> Processing Dependency: elfutils-devel for package: 1:net-snmp-devel-5.5-54.el6_7.1.x86_64
--> Processing Dependency: libsnmp.so.20()(64bit) for package: 1:net-snmp-devel-5.5-54.el6_7.1.x86_64
--> Processing Dependency: libnetsnmptrapd.so.20()(64bit) for package: 1:net-snmp-devel-5.5-54.el6_7.1.x86_64
--> Processing Dependency: libnetsnmpmibs.so.20()(64bit) for package: 1:net-snmp-devel-5.5-54.el6_7.1.x86_64
--> Processing Dependency: libnetsnmphelpers.so.20()(64bit) for package: 1:net-snmp-devel-5.5-54.el6_7.1.x86_64
--> Processing Dependency: libnetsnmpagent.so.20()(64bit) for package: 1:net-snmp-devel-5.5-54.el6_7.1.x86_64
--> Processing Dependency: libnetsnmp.so.20()(64bit) for package: 1:net-snmp-devel-5.5-54.el6_7.1.x86_64
---> Package newt-devel.x86_64 0:0.52.11-3.el6 will be installed
--> Processing Dependency: newt = 0.52.11-3.el6 for package: newt-devel-0.52.11-3.el6.x86_64
--> Processing Dependency: slang-devel for package: newt-devel-0.52.11-3.el6.x86_64
--> Processing Dependency: libnewt.so.0.52()(64bit) for package: newt-devel-0.52.11-3.el6.x86_64
---> Package openssl-devel.x86_64 0:1.0.1e-42.el6_7.4 will be installed
--> Processing Dependency: krb5-devel for package: openssl-devel-1.0.1e-42.el6_7.4.x86_64
---> Package sqlite-devel.x86_64 0:3.6.20-1.el6_7.2 will be installed
---> Package xinetd.x86_64 2:2.3.14-39.el6_4 will be installed
--> Processing Dependency: initscripts for package: 2:xinetd-2.3.14-39.el6_4.x86_64
--> Processing Dependency: /sbin/service for package: 2:xinetd-2.3.14-39.el6_4.x86_64
--> Processing Dependency: libwrap.so.0()(64bit) for package: 2:xinetd-2.3.14-39.el6_4.x86_64
--> Running transaction check
---> Package cloog-ppl.x86_64 0:0.15.7-1.2.el6 will be installed
--> Processing Dependency: libppl_c.so.2()(64bit) for package: cloog-ppl-0.15.7-1.2.el6.x86_64
--> Processing Dependency: libppl.so.7()(64bit) for package: cloog-ppl-0.15.7-1.2.el6.x86_64
---> Package elfutils-devel.x86_64 0:0.161-3.el6 will be installed
--> Processing Dependency: elfutils-libs(x86-64) = 0.161-3.el6 for package: elfutils-devel-0.161-3.el6.x86_64
--> Processing Dependency: libdw.so.1()(64bit) for package: elfutils-devel-0.161-3.el6.x86_64
--> Processing Dependency: libasm.so.1()(64bit) for package: elfutils-devel-0.161-3.el6.x86_64
---> Package elfutils-libelf-devel.x86_64 0:0.161-3.el6 will be installed
---> Package glibc-devel.x86_64 0:2.12-1.166.el6_7.7 will be installed
--> Processing Dependency: glibc-headers = 2.12-1.166.el6_7.7 for package: glibc-devel-2.12-1.166.el6_7.7.x86_64
--> Processing Dependency: glibc-headers for package: glibc-devel-2.12-1.166.el6_7.7.x86_64
---> Package initscripts.x86_64 0:9.03.49-1.el6.centos.5 will be installed
--> Processing Dependency: util-linux-ng >= 2.16 for package: initscripts-9.03.49-1.el6.centos.5.x86_64
--> Processing Dependency: udev >= 125-1 for package: initscripts-9.03.49-1.el6.centos.5.x86_64
--> Processing Dependency: sysvinit-tools >= 2.87-6 for package: initscripts-9.03.49-1.el6.centos.5.x86_64
--> Processing Dependency: /sbin/pidof for package: initscripts-9.03.49-1.el6.centos.5.x86_64
--> Processing Dependency: /sbin/ip for package: initscripts-9.03.49-1.el6.centos.5.x86_64
--> Processing Dependency: /sbin/blkid for package: initscripts-9.03.49-1.el6.centos.5.x86_64
--> Processing Dependency: /sbin/arping for package: initscripts-9.03.49-1.el6.centos.5.x86_64
---> Package krb5-devel.x86_64 0:1.10.3-42z1.el6_7 will be installed
--> Processing Dependency: libselinux-devel for package: krb5-devel-1.10.3-42z1.el6_7.x86_64
--> Processing Dependency: libcom_err-devel for package: krb5-devel-1.10.3-42z1.el6_7.x86_64
--> Processing Dependency: keyutils-libs-devel for package: krb5-devel-1.10.3-42z1.el6_7.x86_64
---> Package libgomp.x86_64 0:4.4.7-16.el6 will be installed
---> Package libstdc++-devel.x86_64 0:4.4.7-16.el6 will be installed
---> Package lm_sensors-devel.x86_64 0:3.1.1-17.el6 will be installed
--> Processing Dependency: lm_sensors-libs(x86-64) = 3.1.1-17.el6 for package: lm_sensors-devel-3.1.1-17.el6.x86_64
--> Processing Dependency: libsensors.so.4()(64bit) for package: lm_sensors-devel-3.1.1-17.el6.x86_64
---> Package mpfr.x86_64 0:2.4.1-6.el6 will be installed
---> Package net-snmp-libs.x86_64 1:5.5-54.el6_7.1 will be installed
--> Processing Dependency: perl(:MODULE_COMPAT_5.10.1) for package: 1:net-snmp-libs-5.5-54.el6_7.1.x86_64
--> Processing Dependency: libperl.so()(64bit) for package: 1:net-snmp-libs-5.5-54.el6_7.1.x86_64
---> Package newt.x86_64 0:0.52.11-3.el6 will be installed
--> Processing Dependency: libslang.so.2(SLANG2)(64bit) for package: newt-0.52.11-3.el6.x86_64
--> Processing Dependency: libslang.so.2()(64bit) for package: newt-0.52.11-3.el6.x86_64
---> Package rpm-devel.x86_64 0:4.8.0-47.el6 will be installed
--> Processing Dependency: popt-devel(x86-64) for package: rpm-devel-4.8.0-47.el6.x86_64
--> Processing Dependency: file-devel(x86-64) for package: rpm-devel-4.8.0-47.el6.x86_64
---> Package slang-devel.x86_64 0:2.2.1-1.el6 will be installed
---> Package tcp_wrappers-devel.x86_64 0:7.6-57.el6 will be installed
---> Package tcp_wrappers-libs.x86_64 0:7.6-57.el6 will be installed
---> Package zlib-devel.x86_64 0:1.2.3-29.el6 will be installed
--> Running transaction check
---> Package elfutils-libs.x86_64 0:0.161-3.el6 will be installed
---> Package file-devel.x86_64 0:5.04-21.el6 will be installed
---> Package glibc-headers.x86_64 0:2.12-1.166.el6_7.7 will be installed
---> Package iproute.x86_64 0:2.6.32-45.el6 will be installed
--> Processing Dependency: iptables >= 1.4.5 for package: iproute-2.6.32-45.el6.x86_64
--> Processing Dependency: libxtables.so.4()(64bit) for package: iproute-2.6.32-45.el6.x86_64
---> Package iputils.x86_64 0:20071127-20.el6 will be installed
---> Package keyutils-libs-devel.x86_64 0:1.4-5.el6 will be installed
---> Package libcom_err-devel.x86_64 0:1.41.12-22.el6 will be installed
---> Package libselinux-devel.x86_64 0:2.0.94-5.8.el6 will be installed
--> Processing Dependency: libsepol-devel >= 2.0.32-1 for package: libselinux-devel-2.0.94-5.8.el6.x86_64
--> Processing Dependency: pkgconfig(libsepol) for package: libselinux-devel-2.0.94-5.8.el6.x86_64
---> Package lm_sensors-libs.x86_64 0:3.1.1-17.el6 will be installed
---> Package perl.x86_64 4:5.10.1-141.el6_7.1 will be installed
--> Processing Dependency: perl(version) for package: 4:perl-5.10.1-141.el6_7.1.x86_64
--> Processing Dependency: perl(Pod::Simple) for package: 4:perl-5.10.1-141.el6_7.1.x86_64
--> Processing Dependency: perl(Module::Pluggable) for package: 4:perl-5.10.1-141.el6_7.1.x86_64
---> Package perl-libs.x86_64 4:5.10.1-141.el6_7.1 will be installed
---> Package popt-devel.x86_64 0:1.13-7.el6 will be installed
---> Package ppl.x86_64 0:0.10.2-11.el6 will be installed
---> Package slang.x86_64 0:2.2.1-1.el6 will be installed
---> Package sysvinit-tools.x86_64 0:2.87-6.dsf.el6 will be installed
---> Package udev.x86_64 0:147-2.63.el6_7.1 will be installed
--> Processing Dependency: hwdata for package: udev-147-2.63.el6_7.1.x86_64
---> Package util-linux-ng.x86_64 0:2.17.2-12.18.el6 will be installed
--> Running transaction check
---> Package hwdata.noarch 0:0.233-14.1.el6 will be installed
---> Package iptables.x86_64 0:1.4.7-16.el6 will be installed
--> Processing Dependency: policycoreutils for package: iptables-1.4.7-16.el6.x86_64
---> Package libsepol-devel.x86_64 0:2.0.41-4.el6 will be installed
---> Package perl-Module-Pluggable.x86_64 1:3.90-141.el6_7.1 will be installed
---> Package perl-Pod-Simple.x86_64 1:3.13-141.el6_7.1 will be installed
--> Processing Dependency: perl(Pod::Escapes) >= 1.04 for package: 1:perl-Pod-Simple-3.13-141.el6_7.1.x86_64
---> Package perl-version.x86_64 3:0.77-141.el6_7.1 will be installed
--> Running transaction check
---> Package perl-Pod-Escapes.x86_64 1:1.04-141.el6_7.1 will be installed
---> Package policycoreutils.x86_64 0:2.0.83-24.el6 will be installed
--> Processing Dependency: libdbus-glib-1.so.2()(64bit) for package: policycoreutils-2.0.83-24.el6.x86_64
--> Running transaction check
---> Package dbus-glib.x86_64 0:0.86-6.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package                  Arch      Version                    Repository  Size
================================================================================
Installing:
 cpp                      x86_64    4.4.7-16.el6               base       3.7 M
 gcc                      x86_64    4.4.7-16.el6               base        10 M
 gcc-c++                  x86_64    4.4.7-16.el6               base       4.7 M
 kernel-devel             x86_64    2.6.32-573.26.1.el6        updates     10 M
 kernel-headers           x86_64    2.6.32-573.26.1.el6        updates    3.9 M
 libuuid-devel            x86_64    2.17.2-12.18.el6           base        85 k
 libxml2-devel            x86_64    2.7.6-20.el6_7.1           updates    1.1 M
 ncurses-devel            x86_64    5.7-4.20090207.el6         base       641 k
 net-snmp-devel           x86_64    1:5.5-54.el6_7.1           updates    306 k
 newt-devel               x86_64    0.52.11-3.el6              base        47 k
 openssl-devel            x86_64    1.0.1e-42.el6_7.4          updates    1.2 M
 sqlite-devel             x86_64    3.6.20-1.el6_7.2           updates     81 k
 xinetd                   x86_64    2:2.3.14-39.el6_4          base       121 k
Installing for dependencies:
 cloog-ppl                x86_64    0.15.7-1.2.el6             base        93 k
 dbus-glib                x86_64    0.86-6.el6                 base       170 k
 elfutils-devel           x86_64    0.161-3.el6                base        77 k
 elfutils-libelf-devel    x86_64    0.161-3.el6                base        31 k
 elfutils-libs            x86_64    0.161-3.el6                base       228 k
 file-devel               x86_64    5.04-21.el6                base        26 k
 glibc-devel              x86_64    2.12-1.166.el6_7.7         updates    986 k
 glibc-headers            x86_64    2.12-1.166.el6_7.7         updates    615 k
 hwdata                   noarch    0.233-14.1.el6             base       1.3 M
 initscripts              x86_64    9.03.49-1.el6.centos.5     updates    945 k
 iproute                  x86_64    2.6.32-45.el6              base       367 k
 iptables                 x86_64    1.4.7-16.el6               base       254 k
 iputils                  x86_64    20071127-20.el6            base       120 k
 keyutils-libs-devel      x86_64    1.4-5.el6                  base        29 k
 krb5-devel               x86_64    1.10.3-42z1.el6_7          updates    502 k
 libcom_err-devel         x86_64    1.41.12-22.el6             base        33 k
 libgomp                  x86_64    4.4.7-16.el6               base       134 k
 libselinux-devel         x86_64    2.0.94-5.8.el6             base       137 k
 libsepol-devel           x86_64    2.0.41-4.el6               base        64 k
 libstdc++-devel          x86_64    4.4.7-16.el6               base       1.6 M
 lm_sensors-devel         x86_64    3.1.1-17.el6               base        22 k
 lm_sensors-libs          x86_64    3.1.1-17.el6               base        38 k
 mpfr                     x86_64    2.4.1-6.el6                base       157 k
 net-snmp-libs            x86_64    1:5.5-54.el6_7.1           updates    1.5 M
 newt                     x86_64    0.52.11-3.el6              base        97 k
 perl                     x86_64    4:5.10.1-141.el6_7.1       updates     10 M
 perl-Module-Pluggable    x86_64    1:3.90-141.el6_7.1         updates     40 k
 perl-Pod-Escapes         x86_64    1:1.04-141.el6_7.1         updates     33 k
 perl-Pod-Simple          x86_64    1:3.13-141.el6_7.1         updates    213 k
 perl-libs                x86_64    4:5.10.1-141.el6_7.1       updates    579 k
 perl-version             x86_64    3:0.77-141.el6_7.1         updates     52 k
 policycoreutils          x86_64    2.0.83-24.el6              base       651 k
 popt-devel               x86_64    1.13-7.el6                 base        21 k
 ppl                      x86_64    0.10.2-11.el6              base       1.3 M
 rpm-devel                x86_64    4.8.0-47.el6               base        95 k
 slang                    x86_64    2.2.1-1.el6                base       473 k
 slang-devel              x86_64    2.2.1-1.el6                base        94 k
 sysvinit-tools           x86_64    2.87-6.dsf.el6             base        60 k
 tcp_wrappers-devel       x86_64    7.6-57.el6                 base        15 k
 tcp_wrappers-libs        x86_64    7.6-57.el6                 base        62 k
 udev                     x86_64    147-2.63.el6_7.1           updates    355 k
 util-linux-ng            x86_64    2.17.2-12.18.el6           base       1.6 M
 zlib-devel               x86_64    1.2.3-29.el6               base        44 k

Transaction Summary
================================================================================
Install      56 Package(s)

Total download size: 61 M
Installed size: 169 M
Downloading Packages:
--------------------------------------------------------------------------------
Total                                           2.1 MB/s |  61 MB     00:29
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : tcp_wrappers-libs-7.6-57.el6.x86_64                         1/56
  Installing : lm_sensors-libs-3.1.1-17.el6.x86_64                         2/56
  Installing : elfutils-libelf-devel-0.161-3.el6.x86_64                    3/56
  Installing : slang-2.2.1-1.el6.x86_64                                    4/56
  Installing : zlib-devel-1.2.3-29.el6.x86_64                              5/56
  Installing : mpfr-2.4.1-6.el6.x86_64                                     6/56
  Installing : sysvinit-tools-2.87-6.dsf.el6.x86_64                        7/56
  Installing : cpp-4.4.7-16.el6.x86_64                                     8/56
  Installing : newt-0.52.11-3.el6.x86_64                                   9/56
  Installing : slang-devel-2.2.1-1.el6.x86_64                             10/56
  Installing : lm_sensors-devel-3.1.1-17.el6.x86_64                       11/56
  Installing : tcp_wrappers-devel-7.6-57.el6.x86_64                       12/56
  Installing : 1:perl-Pod-Escapes-1.04-141.el6_7.1.x86_64                 13/56
  Installing : 1:perl-Pod-Simple-3.13-141.el6_7.1.x86_64                  14/56
  Installing : 3:perl-version-0.77-141.el6_7.1.x86_64                     15/56
  Installing : 4:perl-libs-5.10.1-141.el6_7.1.x86_64                      16/56
  Installing : 1:perl-Module-Pluggable-3.90-141.el6_7.1.x86_64            17/56
  Installing : 4:perl-5.10.1-141.el6_7.1.x86_64                           18/56
  Installing : 1:net-snmp-libs-5.5-54.el6_7.1.x86_64                      19/56
  Installing : dbus-glib-0.86-6.el6.x86_64                                20/56
  Installing : kernel-headers-2.6.32-573.26.1.el6.x86_64                  21/56
  Installing : glibc-headers-2.12-1.166.el6_7.7.x86_64                    22/56
  Installing : glibc-devel-2.12-1.166.el6_7.7.x86_64                      23/56
  Installing : libsepol-devel-2.0.41-4.el6.x86_64                         24/56
  Installing : libselinux-devel-2.0.94-5.8.el6.x86_64                     25/56
  Installing : ppl-0.10.2-11.el6.x86_64                                   26/56
  Installing : cloog-ppl-0.15.7-1.2.el6.x86_64                            27/56
  Installing : libstdc++-devel-4.4.7-16.el6.x86_64                        28/56
  Installing : keyutils-libs-devel-1.4-5.el6.x86_64                       29/56
  Installing : popt-devel-1.13-7.el6.x86_64                               30/56
  Installing : hwdata-0.233-14.1.el6.noarch                               31/56
  Installing : policycoreutils-2.0.83-24.el6.x86_64                       32/56
  Installing : iptables-1.4.7-16.el6.x86_64                               33/56
  Installing : iproute-2.6.32-45.el6.x86_64                               34/56
  Installing : iputils-20071127-20.el6.x86_64                             35/56
  Installing : util-linux-ng-2.17.2-12.18.el6.x86_64                      36/56
install-info: No such file or directory for /usr/share/info/ipc.info
  Installing : initscripts-9.03.49-1.el6.centos.5.x86_64                  37/56
  Installing : udev-147-2.63.el6_7.1.x86_64                               38/56
  Installing : elfutils-libs-0.161-3.el6.x86_64                           39/56
  Installing : elfutils-devel-0.161-3.el6.x86_64                          40/56
  Installing : libcom_err-devel-1.41.12-22.el6.x86_64                     41/56
  Installing : krb5-devel-1.10.3-42z1.el6_7.x86_64                        42/56
  Installing : openssl-devel-1.0.1e-42.el6_7.4.x86_64                     43/56
  Installing : file-devel-5.04-21.el6.x86_64                              44/56
  Installing : rpm-devel-4.8.0-47.el6.x86_64                              45/56
  Installing : libgomp-4.4.7-16.el6.x86_64                                46/56
  Installing : gcc-4.4.7-16.el6.x86_64                                    47/56
  Installing : gcc-c++-4.4.7-16.el6.x86_64                                48/56
  Installing : 1:net-snmp-devel-5.5-54.el6_7.1.x86_64                     49/56
  Installing : 2:xinetd-2.3.14-39.el6_4.x86_64                            50/56
  Installing : newt-devel-0.52.11-3.el6.x86_64                            51/56
  Installing : libxml2-devel-2.7.6-20.el6_7.1.x86_64                      52/56
  Installing : kernel-devel-2.6.32-573.26.1.el6.x86_64                    53/56
  Installing : ncurses-devel-5.7-4.20090207.el6.x86_64                    54/56
  Installing : libuuid-devel-2.17.2-12.18.el6.x86_64                      55/56
  Installing : sqlite-devel-3.6.20-1.el6_7.2.x86_64                       56/56

Rpmdb checksum is invalid: dCDPT(pkg checksums): libgomp.x86_64 0:4.4.7-16.el6 - u

The command '/bin/sh -c yum install kernel-headers gcc gcc-c++ cpp ncurses ncurses-devel libxml2 libxml2-devel sqlite sqlite-devel openssl-devel newt-devel kernel-devel libuuid-devel net-snmp-devel xinetd tar -y' returned a non-zero code: 1
```

**Comment by dougbtv** [comment] 2016-05-14 23:54
Interesting find. I figured up 899.9.0 and reproduced it in the same exact manner.

Turns out it's an obscure bug in CentOS (CentOS being the base image for this Dockerfile) that's exposed here when using overlayFS, which the default storage driver for CoreOS (and a good choice). 

Here's the domino that starts it all, I guess:

```
Last login: Sat May 14 23:07:39 2016 from 192.168.122.1
CoreOS beta (899.9.0)
core@coreos5 ~ $ docker info
Containers: 6
Images: 27
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.3.6-coreos
Operating System: CoreOS 899.9.0
CPUs: 1
Total Memory: 997.3 MiB
Name: coreos5
ID: MJWM:NRZO:OVQO:KMHI:4YFV:5DKO:BDRR:LDBC:4KCN:525D:DCMZ:TP5U
```

More info on it here: https://github.com/docker/docker/issues/10180

Given what I saw for work-arounds, it wasn't pretty. So I decided to update the base image to CentOS7, which appears to do the trick nicely (supposedly the fix on the CentOS side has made it officially into upstream), and... it's about time, really, to use CentOS7.

Just manually tested and it looks good so far as building it. 

I'm going to open a PR, which I'll reference here, but, some further debugging is needed it didn't pass it's Travis build. If you do a `git checkout fixcore` after your `git clone` and then build, you'll see it build at least.

**Comment by dougbtv** [comment] 2016-05-15 11:17
Update to CentOS 7 is working -- and should work for a build under CoreOS now too, all merged into master. Let me know if you run into any snags.

**Comment by themicster** [comment] 2016-05-15 19:21
Yup, that fixed it. Can you get this changed in the other Dockerfiles's as well?

**Comment by themicster** [comment] 2016-05-15 19:35
I tried building asterisk 13 by just changing to centos7 but it gave me this error:
/bin/sh: make: command not found
Might need to add some more packages to the yum command

**Comment by dougbtv** [comment] 2016-05-15 19:45
I've almost got it for Asterisk 13, wound up changing it while addressing another issue, should be merging it in this afternoon. 

After that I think the only straggler are dougbtv/kamailio & dougbtv/fastagi

**Comment by dougbtv** [comment] 2016-05-15 21:54
Alright, I merged in those changes -- give 'er a whirl at will. NB the kamailio image doesn't have any CI, which I gotta add a todo, so.... it's sorta untested, it's just a couple minor versions ahead so it should be JustFine™

**Comment by themicster** [comment] 2016-05-15 23:55
trouble building captagent

/bin/sh: ./build.sh: No such file or directory

**Comment by dougbtv** [comment] 2016-05-16 00:10
capt-agent has undergone a lot of improvements since this dockerfile. and it's breaking changes, and that dockerfile tracks HEAD on master. which isn't... ideal. I'll open a new issue.

**Comment by dougbtv** [comment] 2016-05-16 00:13
I've got it in #51 -- I'm going to make this dockerfile work, but, I'm going to deprecate all the Homer stuff herein -- we're maintaining it. I'll contribute back to the Homer guys what I get working here, but...

If you need the image right away, do a `docker pull dougbtv/homer-captagent` (but, the 6.0 / 6.1 changes are better)

**Closed by dougbtv** 2016-05-16 00:14 UTC
